pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url = 'https://maven.fabricmc.net/'
            metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }
        }
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.fabricmc.fabric-loom-remap' || requested.id.id == 'fabric-loom') {
                useModule("net.fabricmc:fabric-loom:${requested.version}")
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    id 'dev.kikugie.stonecutter' version '0.9.4'
}

include 'fabric'

stonecutter {
    kotlinController = false
    centralScript = 'build.gradle'
    create(getRootProject()) {
        versions '1.21.1', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.1.1', '26.1.2'
        vcsVersion = '26.1.2'
    }
}
