plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '6.0.54'
    id 'idea'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of((findProperty('java_version') ?: '17') as Integer)
}

tasks.named('jar', Jar).configure {
    archiveVersion = "${project.mod_version}-forge-mc${project.minecraft_version}"
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', project.mod_id
            args '--nogui'
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', project.mod_id, '--all',
                    '--output', rootProject.file('src/generated/resources/'),
                    '--existing', rootProject.file('src/main/resources/')
        }
    }
}

sourceSets {
    main {
        java.setSrcDirs([
                rootProject.file('src/main/java'),
                rootProject.file('src/common/java'),
                rootProject.file('src/common-minecraft/java')
        ])
        resources.setSrcDirs([
                rootProject.file('src/main/resources'),
                rootProject.file('src/generated/resources')
        ])
    }
    test {
        java.setSrcDirs([
                rootProject.file('src/test/java')
        ])
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    testImplementation platform('org.junit:junit-bom:5.10.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.google.code.gson:gson:2.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from rootProject.file('src/main/templates')
    into layout.buildDirectory.dir("generated/sources/modMetadata")
}

sourceSets.main.resources.srcDir generateModMetadata

tasks.named('jar', Jar).configure {
    finalizedBy 'reobfJar'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url = uri(layout.projectDirectory.dir("repo"))
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
